CREATE TABLE IF NOT EXISTS `mydb`.`inputs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `isAllergic` TINYINT NOT NULL,
  `img` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB