CREATE TABLE IF NOT EXISTS `mydb`.`Insumos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `isAlergico` TINYINT NOT NULL,
  `imagem` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB